GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Syed Haider",
  "dateOfBirth": "1995-03-11",
  "ssn": "ABCDEF123456",
  "gender": "male",
  "occupation": "engineer"
}

###
GET http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667